#!/bin/sh
set -e

echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini
echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini
echo "xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/xdebug.in
echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini
echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/xdebug.ini
echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/xdebug.ini
echo "xdebug.idekey=phpstorm" >> /usr/local/etc/php/conf.d/xdebug.ini
echo "xdebug.remote_host=$DEBUG_IP" >> /usr/local/etc/php/conf.d/xdebug.ini

php-fpm